version: '3.8'

services:
    nginx:
        container_name: symfony-nginx
        build:
            context: .docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/symfony
        depends_on:
            - php-fpm

    php-fpm:
        container_name: symfony-php-fpm
        build:
            context: .docker/php-fpm
            dockerfile: Dockerfile
        environment:
            DB_PORT: 5432
            DB_HOST: postgres
            REDIS_PORT: 6379
            REDIS_HOST: redis
            HISTFILE: '/home/www-data/bash-history/.bash_history'
            PHP_IDE_CONFIG: "serverName=Docker"
        expose:
          - 9000
        volumes:
            - ./:/var/www/symfony
            - symfony-bash-history:/home/www-data/bash-history/:rw
        depends_on:
            - postgres
            - redis
            - rabbitmq

    postgres:
        container_name: symfony-postgres
        image: postgres:15.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: symfony
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

    redis:
        container_name: symfony-redis
        image: redis:7.0.4-alpine
        restart: always
        ports:
            - "63791:6379"

    rabbitmq:
        container_name: symfony-rabbitmq
        build:
            context: .
            dockerfile: .docker/rabbitmq/Dockerfile
        ports:
            - "15672:15672"
            - "5672:5672"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

volumes:
    postgres:
    redis:
    symfony-bash-history:
    rabbitmq-data:
